### ISSUE TITLE
Repeated choices in the sl-cer dataset

### ISSUE THREAD

**Issue by vid-koci** [clarinsi/dialect-copa#1]
Some instances in the sl-cer dataset contain multiple entries for a choice. For example, row 3
`{"﻿choice1": "Kavarna se je znova odprla na novi lokaciji.", "choice2": "Tle sta pačuekat.", "idx": 2, "label": 1, "premise": "Babe sta se dabile na kafitu.", "question": "cause", "choice1": "Kauarna se je adparla na naui lokacij."}`
Contains two fields called "choice1" out of which one seems to be written in the dialect and the other one in formal Slovene.

There seem to be multiple examples like that.

**Comment by nljubesi** [comment]
Thank you for reporting this! This is due to problems with upstream Slovenian data (problems in data encodings in Slovenian SuperGLUE, we jumped through multiple hoops, but this one was still left).

Please check data as this further on and, (thankyou), report issues!

Thanks again!
